run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - gosec
  disable:
    - typecheck

linters-settings:
  errcheck:
    exclude-functions:
      - (*github.com/joho/godotenv).Load
  gosec:
    excludes:
      - G404

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck